# analysis_options.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - annotate_overrides
    - avoid_print
    - prefer_final_fields
    - public_member_api_docs
    - sort_constructors_first
    - sort_pub_dependencies
    - type_annotate_public_apis
    - unnecessary_getters_setters
    - use_key_in_widget_constructors